CREATE TABLE 'categories' (
	`category_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`category_name` VARCHAR(100) NOT NULL,
	`description` TEXT DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY (`category_id`)
)ENGINE=InnoDB 
	DEFAULT CHARSET=utf8mb4
	COLLATE=utf8mb4_unicode_ci;